/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minhaCalculadora;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Calculadora calc = new Calculadora();
        System.out.println(calc.somar(5, 6));
        System.out.println(calc.subtrai(10, 6));
         System.out.println(calc.multiplicar(10, 2));
          System.out.println(calc.divisao(8, 2));
        
    }
}
    
